### PR TITLE
Add more providers (L - Z) found in data

### PR DESCRIPTION
**Pull request by shashank025**
See CAVaccineInventory/vaccine-feed-ingest#254 and CAVaccineInventory/vaccine-feed-ingest#332 for context.

This PR does 3 things:

1. Adds remaining providers (names starting **_L_** through **_Z_**) found in the data source
2. Sorts the VaccineProviders enum to make it easier to avoid duplicates
~~3. Identifies some previously added enums (_e.g._, `KING_SOOPER`) as subsidiaries of others (_e.g._,`KROGER`) and calls for their removal. This PR does _not_ remove it from the enum, since that **_might_** break things? Happy to hear from reviewers how to do this safely...~~

Separately, https://github.com/CAVaccineInventory/vaccine-feed-ingest/pull/360 is being prepared to update the `provider_id_from_name()` method to account for these newly added providers.

After this PR is merged, all the pharmacies listed at https://www.cdc.gov/vaccines/covid-19/retail-pharmacy-program/participating-pharmacies.html should be represented in the schema

### CODE REVIEW

**Comment by shashank025** [comment]
Should I also bump the version like with https://github.com/CAVaccineInventory/vaccine-feed-ingest-schema/pull/20?

**Comment by shashank025** [comment]
I need to make some more updates. Not ready to merge yet ...

**Comment by shashank025** [comment]
Ready for review + merge.

**Review by bryanculbertson — CHANGES_REQUESTED** [review]
I don't think we should collapse provider IDs by owning corporation.

1. I think it is more important to record the brand of store than the corporation because users interact with the brand more than the corporation.
2. The brand has more fidelity, as long as we record the brand, we can later use that to lookup the corporation if we need it.
3. Brands have their own store IDs. We don't want to combine Albertsons #5301 with Safeway #5301 because those are different stores.

**Comment by shashank025** [comment]
> I don't think we should collapse provider IDs by owning corporation.

Done!

**Review by bryanculbertson — APPROVED** [review]

**Pull request merged**
